version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5555
      POSTGRES_DB: docker_proj
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend/api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:5555@db:5432/docker_proj"

volumes:
  postgres_data:
